SET(SMEDIA_DEFS
    -DMM9910
    -DSDK_MAJOR_VERSION=${SDK_MAJOR_VERSION}
    -DSDK_MINOR_VERSION=${SDK_MINOR_VERSION}
    )

SET(SMEDIA_INC_DIRS
    ${PROJECT_SOURCE_DIR}/sdk/include
    ${PROJECT_SOURCE_DIR}/sdk/share/fat
    ${PROJECT_SOURCE_DIR}/sdk/share/fat/common
    )

ADD_DEFINITIONS(${SMEDIA_DEFS})
SET(BUILD_SHARED_LIBS ON)
