set(CFG_BUILD_NOR 1)
set(CFG_BUILD_MMP 1)
set(CFG_BUILD_SPI 1)
set(CFG_BUILD_DMA 1)
set(CFG_BUILD_INTR 1)

SET(SMEDIA_DEFS
    -D__OR32__
    -D__FREERTOS__
    -DMM9910
    -DCFG_OSC_CLK=12000000
    -DIDLE_TASK
    -DRTOS_USE_ISR
    -DMEMORY_SIZE=64M
    -DENABLE_CODECS_PLUGIN
    -DCUSTOMER_CODE=${CUSTOMER_CODE}
    -DPROJECT_CODE=${PROJECT_CODE}
    -DSDK_MAJOR_VERSION=${SDK_MAJOR_VERSION}
    -DSDK_MINOR_VERSION=${SDK_MINOR_VERSION}
    -DBUILD_NUMBER=${BUILD_NUMBER}
)

IF(${CONFIG_HAVE_NTFS})
    SET(SMEDIA_DEFS
        ${SMEDIA_DEFS}
        -DCONFIG_HAVE_NTFS=1
    )
ENDIF()

# avoid build warning
SET(CMAKE_TOOLCHAIN_FILE ${CMAKE_TOOLCHAIN_FILE})

SET(JEDI_ROM_INIT_SCRIPT "IT9919_A1_Initial_DDR2_Mem_notiling_440MHZ.scr")

SET(SMEDIA_INC_DIRS
    ${PROJECT_SOURCE_DIR}/${SMEDIA_PLATFORM}/include/or32
    ${PROJECT_SOURCE_DIR}/${SMEDIA_PLATFORM}/include/freertos
    ${PROJECT_SOURCE_DIR}/sdk/include
    ${PROJECT_SOURCE_DIR}/sdk/share/fat
    ${PROJECT_SOURCE_DIR}/sdk/share/fat/common
)

ADD_DEFINITIONS(${SMEDIA_DEFS})
SET(LIBRARY_OUTPUT_PATH ${PROJECT_BINARY_DIR}/lib)
SET(CMAKE_C_FLAGS_DEBUG "-g -mcmov -DDEBUG -mhard-div -fno-short-enums -gstabs")
SET(CMAKE_C_FLAGS_RELEASE "-g3 -Os -mcmov -DNDEBUG -mhard-div -fno-short-enums -gstabs")
SET(CMAKE_CXX_FLAGS_DEBUG "-g -mcmov -DDEBUG -mhard-div -fno-short-enums -gstabs")
SET(CMAKE_CXX_FLAGS_RELEASE "-g3 -Os -mcmov -DNDEBUG -mhard-div -fno-short-enums -gstabs")

SET(CMAKE_EXE_LINKER_FLAGS "-nostartfiles -T${LIBRARY_OUTPUT_PATH}/default.ld -L${LIBRARY_OUTPUT_PATH} ${LIBRARY_OUTPUT_PATH}/or32_crt0.o")

#CHIP_VERSION
IF(${CHIP_VERSION} STREQUAL IT9917_176TQFP)
    ADD_DEFINITIONS(
        -DIT9917_176TQFP
    )
ELSEIF(${CHIP_VERSION} STREQUAL IT9913_128LQFP)
    ADD_DEFINITIONS(
        -DIT9913_128LQFP
    )
ELSEIF(${CHIP_VERSION} STREQUAL IT9919_144TQFP)
    ADD_DEFINITIONS(
        -DIT9919_144TQFP
    )
ENDIF()

#BOARD_MODULE
IF(${BOARD_MODULE} STREQUAL EVB_BOARD)
    ADD_DEFINITIONS(
        -DEVB_BOARD
    )
ELSEIF(${BOARD_MODULE} STREQUAL REF_BOARD_AVSENDER)
    ADD_DEFINITIONS(
        -DREF_BOARD_AVSENDER
    )
ELSEIF(${BOARD_MODULE} STREQUAL REF_BOARD_CAMERA)
    ADD_DEFINITIONS(
        -DREF_BOARD_CAMERA
    )
ENDIF()