@echo off
rem if not exist freertos-config.cmd call freertos-setting.cmd
call freertos-config.cmd
call ..\version.cmd
@echo -- SDK Version: %CUSTOMER_CODE%.%PROJECT_CODE%.%SDK_MAJOR_VERSION%.%SDK_MINOR_VERSION%.%BUILD_NUMBER%
for /f %%a in ('cd') do set CMAKE_ROOT=%%a\..\..\tool
for /f "tokens=3 delims=() " %%a in ('find "CMAKE_FIND_ROOT_PATH " ..\..\freertos\toolchain.cmake') do set toolchain=%%a
set toolchain=%toolchain:/=\%
set PATH=%CMAKE_ROOT%\bin;%toolchain%\bin;%PATH%
if not exist freertos mkdir freertos
cd freertos
if exist project\%PROJECT_TYPE%\jedi del project\%PROJECT_TYPE%\jedi
cmake.exe -G"Unix Makefiles" -DCONFIG_HAVE_NTFS=%CONFIG_HAVE_NTFS% -DCONFIG_USBD_HAVE_PCGRABBER=%CONFIG_USBD_HAVE_PCGRABBER% -DCONFIG_HAVE_USBD=%CONFIG_HAVE_USBD% -DEXTERNAL_RTC=%EXTERNAL_RTC% -DUSB_DEVICE=%USB_DEVICE% -DUSB_STORAGE=%USB_STORAGE% -DSD_STORAGE=%SD_STORAGE% -DTSO_MODULE=%TSO_MODULE% -DEXTERNAL_HDMIRX=%EXTERNAL_HDMIRX% -DHDMI_LOOPTHROUGH=%HDMI_LOOPTHROUGH% -DCOMPONENT_DEV=%COMPONENT_DEV% -DHDCP_ON=%HDCP_ON% -DSENSOR_DEV=%SENSOR_DEV% -DSENSOR_ID=%SENSOR_ID% -DCHIP_VERSION=%CHIP_VERSION% -DCOMPOSITE_DEV=%COMPOSITE_DEV% -DCUSTOMER_CODE=%CUSTOMER_CODE% -DPROJECT_CODE=%PROJECT_CODE% -DSDK_MAJOR_VERSION=%SDK_MAJOR_VERSION% -DSDK_MINOR_VERSION=%SDK_MINOR_VERSION% -DBUILD_NUMBER=%BUILD_NUMBER% -DSMEDIA_PLATFORM=freertos -DSYSTEM_FAT_TYPE=%SYSTEM_FAT_TYPE% -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DPROJECT_TYPE=%PROJECT_TYPE% -DMULTIPLE_INSTANCES=%MULTIPLE_INSTANCES% -DBOARD_MODULE=%BOARD_MODULE% -DMENCODER=DISABLE -DCMAKE_TOOLCHAIN_FILE=..\..\..\freertos\toolchain.cmake ..\..\..
rem make VERBOSE=1
set CYGWIN=nodosfilewarning
make -j4
cd ..\
@if not defined NO_PAUSE pause
